### ISSUE TITLE
Would RenderFlow continue to develop?

### ISSUE THREAD

**Issue by Xayah-Hina** [CubbyFlow/RenderFlow#10]
It seems RenderFlow did not function well yet... So would it to be updated in the future? ^_^

**Comment by utilForever** [comment]
@Snowapril Can you answer this?

**Comment by Snowapril** [comment]
Hello. Thanks for having an interest in this project. I'm a little bit busy these days that I can't afford to work. I plan to resume work around next year.

The project's initial plan was aimed at building Vulkan renderer from the bottom up to fluid simulation. 
These days, however, I'm considering using a well-made rendering framework to implement a visualization tool that just will help implement new algorithms in CubbyFlow.
